name: ves_qc
description: Field-ready 1-D ERT/VES QC companion for geophysicists.
version: 0.1.0+1
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  fl_chart: ^0.66.0
  csv: ^6.0.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  collection: ^1.18.0
  intl: ^0.18.1
  path: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/samples/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
