[approvals]
require = true

[commands]
allow = ["bash scripts/ci/test_wsl.sh",
         "flutter pub get", "dart format . --fix",
         "flutter analyze", "flutter test -x widget_dialog"]

[sandbox]
allow_network = false
