name: resicheck
description: ResiCheck — field-ready 1-D ERT/VES resistivity QC companion for geophysicists.
version: 0.1.0+1
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  fl_chart: ^1.1.1
  csv: ^6.0.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  collection: ^1.18.0
  intl: ^0.20.2
  path: ^1.9.0
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  excel: ^4.0.6
  syncfusion_flutter_xlsio: ^29.2.11
  file_picker: ^10.3.3
  geolocator: ^14.0.2
  geolocator_linux: ^0.2.0
  pdf: ^3.10.7
  printing: ^5.11.0
  archive: ^3.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/samples/sample_project.json
    - assets/samples/Wenner1D.csv
    - assets/samples/Schlum1D.csv
    - assets/templates/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
