name: Flutter CI (Windows)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Restore Pub cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}\.dart_tool
          key: pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            pub-${{ runner.os }}-

      - name: Get dependencies
        run: flutter pub get

      - name: Format check
        run: dart format . --set-exit-if-changed

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test -x widget_dialog --reporter expanded

      - name: Upload artifacts (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: flutter-test-logs
          path: build
